apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBTEirdooxf0EnjxBdQTAEUuFiHsHngPKBmZh9zpAGukv2r/MbOW5ehtkEaeJTfWPoFUCspQb6A63AMpznXmfpD4gZ4c40sgGKQqZfuK6pPfwocwVn1DahV8yzTWpy5Dnm7zzHRfT7uawv8XCojZsbixpttNGtxz8WPpWfxnxCwEPb2pNTrtaPt18+upxagna8RX0QQmUaaQxUo0sW0aXsLdKXFox1A3Z0InaT4fad6OveUPEDDJ/lvVTXYNTauSZ1nRK0GkTsnJlAjOuAu/5rsLYmDnZkRr19PvXq46BbPU5X3giz4C4T2SsLfiVleNpum5s/rjpDBizjMDpnAYVP6G5gom8X/OHzkcjkmli5kydpSZNkFT25QTOtn3rKocjqxqdJGaVz/UY9MW8tFE0Ja+cgwLnW37kiuVXy3Is9BoXXdsGTagl4n7rVQ7dwUI4Ji6/HnyNuTJtx6vNYJ9fI1A82tucvjSl7zLVx6y521IAj2p9vlDrU5vemsauclIVay04TNZLKqKbgkz9HLZG3UWMf37Mamum5szdUMG/KaaOE5j/naY3caLhwbl/GpM+c9Nt3R9vKNhKHgGjLOmeYiC4YFvTajTgxzvscazqc9v/hAaS5mHZp7AA6SPrahX3AcsrzAO6TpaejGHrKkmONPggIgyvQTWr0lCAb2Q/dilZs0pScmFGMYqiXjxOrgsZ0CEv9Cq/SW8oZAXjY8CizMFvq5Qd2G9V2HYQuPkzrhmvSbV1KVXeS9
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

