apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: MJZYRJ2aXIje-LIHwX_Obw
      keySecretRef:
        name: zerossl-eab
        key: secret

    privateKeySecretRef:
      name: zerossl-prod
    
    solvers:
      - selector:
          dnsNames:
            - ros-nett.com
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
      - selector:
          dnsNames:
            - farr.no
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
