apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  # Cert-Manager installation
  - cert-manager/cert-manager.yaml

  # Credentials
  - credentials/cloudflare-ros-nett-api-token-secret.yaml
  - credentials/zerossl-ros-nett-hmac-key.yaml
  
  # Issuers
  - issuers/zerossl.yaml
  - issuers/letsencrypt.yaml
